routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Facebook api
// EAAQhs75iutUBAPPnnky3EIPAZALwep935ZAJmMv2S9eHbqZBuhtBHv2X1s86lXvtiYU84DZAhxvdvdKXCizeayOwKZCfSOZBvZAhDphnJDqBfjILmcVsjZAZAeZAbr5q0uscC7ftGeG5g70cnZBY7sGMfpkbeMNtg3DTtBLcgnYZAjpXvAZDZD

// Route::domain('revistas.upmaxixe.mock')->group(function () {
//   // SUB DOMAIN
//   Route::get('/', 'RevistasController@index')->name('revistaseartigos');
  
// });


// Route::domain('upmaxixe.mock')->group(function () {
  // MAIN DOMAIN
  Route::get('/', 'PagesController@home')->name('home');
  Route::get('/upengenheiros', 'PagesController@upengenheiros')->name('upengenheiros');
  



  # UNIVERSIDADES TAB
  Route::get('/quemsomos', 'PagesController@quemsomos')->name('quemsomos');
  Route::get('/misseval', 'PagesController@missaoevalores')->name('missaoevalores');
    Route::get('/docentes', 'PagesController@docentes')->name('docentes');
      // Docentes --> Management
      Route::get('/docentes/manage', 'PagesController@docentesmanage')->name('docentes.manage');
      Route::get('/docentes/{id}', 'PagesController@docentesshow');
      Route::post('/docentes/manage/add', 'PagesController@addDocente');
      Route::delete('/docentes/manage/delete/{id}', 'PagesController@deleteDocente'); // delete docente
      Route::get('/docentes/manage/edit/{id}', 'PagesController@editDocente'); // show the edit form
      Route::put('/docentes/manage/edit/{id}', 'PagesController@updateDocente'); // save the edit
  Route::get('/organigrama', 'PagesController@organigrama')->name('organigrama');
  Route::get('/orgaossup', 'PagesController@orgaossuperiores')->name('orgaossuperiores');
  Route::get('/consdirect', 'PagesController@conselhodirectivo')->name('conselhodirectivo');




  # DIRECCAO TAB
  Route::get('/director', 'PagesController@odirector')->name('odirector');
  Route::get('/gabinete', 'PagesController@gabinetedodirector')->name('gabinetedodirector');
  Route::get('/secretaria', 'PagesController@secretariageral')->name('secretariageral');
  Route::get('/registoacademico', 'PagesController@registoacademico')->name('registoacademico');



  
  # COOPERAÇÃO E INTERNACIONALIZAÇÃO TAB
  Route::prefix('/cei')->group(function () { // 'cei' stands for 'cooperação e internacionalização'
    // Matches The "/cei/apresentacao" URL:
    Route::get('/apresentacao', 'CooperacaoController@apresentacao')->name('cei.apresentacao');
      // Matches The "/cei/nacional" URL:
      Route::get('cooperacao/nacional', 'CooperacaoController@cooperacaonacional')->name('cei.cooperacao.nacional');
      // Matches The "/cei/internacional" URL:
      Route::get('cooperacao/internacional', 'CooperacaoController@cooperacaointernacional')->name('cei.cooperacao.internacional');
      
      // Matches The "/cei/internacionalizacao/visiting" URL:
      Route::get('internacionalizacao/visiting', 'CooperacaoController@visiting')->name('cei.internacionalizacao.visiting');
      // Matches The "/cei/internacionalizacao/visiting" URL:
      Route::get('internacionalizacao/professoresconvidados', 'CooperacaoController@professoresconvidados')->name('cei.internacionalizacao.professoresconvidados');
      // Matches The "/cei/internacionalizacao/editais" URL:  
      Route::resource('/internacionalizacao/editais', 'IntEditaisController'); // Route::get('internacionalizacao/editais', 'CooperacaoController@editais')->name('cei.internacionalizacao.editais');
    
    // Matches The "/cei/informacao" URL:  
    Route::get('/informacao', 'CooperacaoController@informacao')->name('cei.informacao');
    // Matches The "/cei/newsletter" URL:  
    Route::get('/newsletter', 'CooperacaoController@newsletter')->name('cei.newsletter');
  });




  # FACULDADES TAB
  Route::get('/faculdades', 'PagesController@faculdades')->name('faculdades');




  # PÓS-GRADUAÇÃO, PESQUISA E EXTENSÃO TAB
  // Route::prefix('/centrosenucleos')->group(function () {
  //   Route::get('/', 'Centros_NucleosController@index')->name('centrosenucleos');
  //   Route::get('/adicionar', 'Centros_NucleosController@create')->name('centrosenucleos.create');
  //   // Route::get('/adicionar', 'Centros_NucleosController@create')->name('centrosenucleos.create');
  // });
  Route::get('/dppe', 'PosGraduacaoController@dppeapresentacao')->name('dppe.apresentacao'); 
  Route::get('/dppe/organigrama', 'PosGraduacaoController@organigrama')->name('dppe.organigrama'); 
  Route::get('/dppe/planoestrategico', 'PosGraduacaoController@planoestrategico')->name('dppe.planoestrategico'); 
  Route::get('/dppe/regulamento', 'PosGraduacaoController@regulamento')->name('dppe.regulamento'); 
  Route::get('/dppe/boletim', 'PosGraduacaoController@boletimdodppe')->name('dppe.boletimdodppe'); 

  Route::resource('/centrosenucleos', 'Centros_NucleosController');
  Route::get('/centrosenucleos/showmodal/{id}', 'Centros_NucleosController@showmodal'); // to retrieve evento's info to show a modal

  Route::get('/dppe/dpp', 'PosGraduacaoController@dppapresentacao')->name('dppe.dpp.apresentacao'); 
  Route::get('/dppe/dpp/projectos', 'PosGraduacaoController@dppprojectos')->name('dppe.dpp.projectos'); 
  Route::get('/dppe/dpp/linhasdepesquisa', 'PosGraduacaoController@dpplinhasdepesquisa')->name('dppe.dpp.linhasdepesquisa'); 

  Route::get('/dppe/dpi', 'PosGraduacaoController@dpiapresentacao')->name('dppe.dpi.apresentacao'); 
  Route::get('/dppe/dpi/projectos', 'PosGraduacaoController@dpiprojectos')->name('dppe.dpi.projectos'); 
  Route::get('/dppe/dpi/escolinhas', 'PosGraduacaoController@dpiescolinhas')->name('dppe.dpi.escolinhas'); 

  Route::get('/dppe/dfp', 'PosGraduacaoController@dfpapresentacao')->name('dppe.dfp.apresentacao'); 
  Route::get('/dppe/dfp/efectivodedocente', 'PosGraduacaoController@dfpefectivodedocente')->name('dppe.dfp.efectivodedocente'); 
  Route::get('/dppe/dfp/docentesporformacao', 'PosGraduacaoController@dfpdocentesporformacao')->name('dppe.dfp.docentesporformacao'); 

  Route::get('/revistas', 'RevistasController@index')->name('dppe.publ.revistaseartigos'); 
  Route::get('/actasdeconferencia', 'PosGraduacaoController@publactasdeconferencia')->name('dppe.publ.actasdeconferencia'); 
  Route::get('/livros', 'PosGraduacaoController@publlivros')->name('dppe.publ.livros'); 
  Route::get('/revistasdeposgraduacao', 'PosGraduacaoController@publrevistasdeposgrad')->name('dppe.publ.revistasdeposgraduacao'); 

  // Route::get('/projectos', 'PagesController@projectosdepesquisa')->name('projectosdepesquisa');
  // Route::get('/revistas', 'RevistasController@index')->name('revistas');
  // Route::get('/escolinhas', 'PagesController@escolinhas')->name('escolinhas');





  # Posts CRUD routes (create, read, upadte, delete)
  Route::resource('/noticias', 'NoticiasController'); // main crud
  Route::post('/noticias/ui/{id}', 'NoticiasController@ui'); // upload image
  Route::get('/noticias/di/{id}/{imageName}', 'NoticiasController@di'); // delete image

  # Eventos CRUD routes (create, read, upadte, delete)
  Route::resource('/eventos', 'EventosController'); // main crud
  Route::get('/eventos/ver/todos', 'EventosController@todos')->name('eventos.todos'); // show all eventos
  Route::get('/eventos/showmodal/{id}', 'EventosController@showmodal'); // to retrieve evento's info to show a modal
  Route::get('/eventos/di/{id}/{imageName}', 'EventosController@di'); // delete image

  # Dashboard Routes
  Route::prefix('/dashboard')->group(function () {
    // Matches The "/dashboard/" URL:
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    // Matches The "/dashboard/destaques" URL:
    Route::get('destaques', 'DashboardController@destaques')->name('dashboard.destaques');

    // To upload images (Matches The "/dashboard/destaques/ui/[id]" URL):
    Route::post('destaques/ui/{id}', 'DashboardController@ui'); // to upload an image
    // To save a destaque (Matches The "/dashboard/destaques/save/[id]" URL):
    Route::post('destaques/save/{id}', 'DashboardController@save'); // to save a destaque
    // To remove a destaque (Matches The "/dashboard/destaques/remove/[id]" URL):
    Route::post('destaques/delete/{id}', 'DashboardController@delete');

    // To show the dialog content
    Route::get('destaques/show/{id}', 'DashboardController@showmodal');
  });

// });


# Authentication Pages Default Routes
Auth::routes();


// Route::group(['prefix' => 'up_ficheiros', 'middleware' => ['web', 'auth']], function () {
//   \UniSharp\LaravelFilemanager\Lfm::routes();
// });


// Route::group(['prefix' => 'up_ficheiros', 'middleware' => ['web', 'auth']], function () {
//   // \UniSharp\LaravelFilemanager\Lfm::routes();
//   // return redirect('/filemanager/dialog.php');
 

// });

Route::get('/up_ficheiros', function () {
  return redirect('/filemanager/dialog.php');
})->middleware(['web', 'auth']);

resources/views/pages/cei/internacionalizacao/editais/create.blade.php
@extends('layouts.app')

@php
 /*
    Must init this variable..
    highlight @section('[mobile]menus')
  */
  $isActive = 'cei';
  $isActiveSub = 'cei.int';
  $isActiveSubSub = 'cei.int.editais';

@endphp

@section('navbar-left-content')
@endsection

@section('navbar-right-content')
  @auth
    @include('inc.navbar-user')
  @endauth
@endsection


@section('headcsslink')
  <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
  {{-- {{ Html::script('../node_modules/tinymce/tinymce.min.js') }}    --}}
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endsection


@section('jscript')
    <script>
      var editor_config = {
        content_css: "{{ asset('css/app.css') }}",
        branding: false,
        autoresize_min_height: 500,
        language_url: "{{ asset('vendor/tinyMCE_notcomposer/langs/pt_PT.js') }}",
        menubar: false,
        path_absolute : "{{ route('home') }}",
        selector: "textarea.my-editor",
        external_plugins: {
          'responsivefilemanager': "{{ asset('vendor/tinyMCE_notcomposer/plugins/responsivefilemanager/plugin.min.js') }}",
        },
        plugins: [
          "autoresize advlist textcolor imagetools charmap autolink lists link image preview hr responsivefilemanager",
          "wordcount visualchars code fullscreen",
          "media table contextmenu directionality",
          "emoticons paste colorpicker"
        ],
        toolbar: "insertfile undo redo | forecolor backcolor | styleselect | bold italic | alignleft aligncenter alignright alignjustify | charmap bullist numlist outdent indent | link image table hr | fullscreen preview",
        relative_urls: false,

        filemanager_title:"UP Maxixe – Ficheiros",
        external_filemanager_path:"/filemanager/",
        file_picker_types: 'file image media',
        file_picker_callback: function(cb, value, meta) {
            var width = window.innerWidth-30;
            var height = window.innerHeight-60;
            if(width > 1800) width=1800;
            if(height > 1200) height=1200;
            if(width>600){
              var width_reduce = (width - 20) % 138;
              width = width - width_reduce + 10;
            }
              var urltype=2;
            if (meta.filetype == 'image') { urltype=1; }
            if (meta.filetype == 'media') { urltype=3; }
            var title = "UP Maxixe – Ficheiros";
            if (typeof this.settings.filemanager_title !== "undefined" && this.settings.filemanager_title) {
              title=this.settings.filemanager_title;
            }
            var akey="key";
            if (typeof this.settings.filemanager_access_key !== "undefined" && this.settings.filemanager_access_key) {
              akey=this.settings.filemanager_access_key;
            }
            var sort_by="";
            if (typeof this.settings.filemanager_sort_by !== "undefined" && this.settings.filemanager_sort_by) {
              sort_by="&sort_by="+this.settings.filemanager_sort_by;
            }
            var descending="false";
            if (typeof this.settings.filemanager_descending !== "undefined" && this.settings.filemanager_descending) {
              descending=this.settings.filemanager_descending;
            }
            var fldr="";
            if (typeof this.settings.filemanager_subfolder !== "undefined" && this.settings.filemanager_subfolder) {
              fldr="&fldr="+this.settings.filemanager_subfolder;
            }
            var crossdomain="";
            if (typeof this.settings.filemanager_crossdomain !== "undefined" && this.settings.filemanager_crossdomain) {
              crossdomain="&crossdomain=1";
              // Add handler for a message from ResponsiveFilemanager
              if(window.addEventListener){
                window.addEventListener('message', filemanager_onMessage, false);
              } else {
                window.attachEvent('onmessage', filemanager_onMessage);
              }
            }

            tinymce.activeEditor.windowManager.open({
              title: title,
              file: this.settings.external_filemanager_path+'dialog.php?type='+urltype+'&descending='+descending+sort_by+fldr+crossdomain+'&lang='+this.settings.language+'&akey='+akey,
              width: width,
              height: height,
              resizable: true,
              maximizable: true,
              inline: 1
            }, {
              setUrl: function (url) {
                cb(url);
              }
            });
        },


      };

      tinymce.init(editor_config);
    </script>

    {{-- tinyMCE k-stylings --}}
     <style>
      .mce-top-part {
        position: relative;
        background-color: white;
      }

      div#mceu_22-body {
        background-color: #eee;
      }
  
      .mce-edit-area {
        background-color: #FFF;
        box-shadow: 0 1px 10px 0px rgba(0, 0, 0, 0.2);
        padding: 1.5cm;
        margin: 30px;
        border-width: 0px 0px 0px !important;
      }
    </style>

@endsection


{{--  Body  --}}
@section('body')
  {!! Form::open(['action' => 'IntEditaisController@store', 'method'=>'POST', 'files'=>'true', 'id' => 'form']) !!}
    <section class="uk-section uk-section-small uk-visible@m">
        <div class="uk-container uk-container-small">

          <div class="uk-alert-primary" uk-alert>
              <small>Cooperação e Internacionalização / Internacionalização</small>
              <h4 class="uk-margin-remove-top"><span style="position: relative; bottom: 2px" uk-icon='plus-circle'> </span>&nbsp Adicionando novo Edital.</h4>
          </div>

          @include('inc.messages')

          <div class="uk-box-shadow-small uk-padding-small uk-align-right uk-navbar-right ">
              <ul class="uk-navbar-nav">
                  {{Form::submit('Publicar', ['class'=>'uk-button uk-button-primary uk-margin-right uk-text-bold'])}}
                  <a href="{{route('editais.index')}}" class="uk-button uk-button-default"> <i style="position: relative; bottom: 1px" uk-icon='arrow-up'></i> Voltar àos Editais</a>
              </ul>
          </div>
        </div>
    </section>

    <!--FORM-->
    <section class="uk-section uk-article uk-section-muted">
        <div class="uk-container uk-container-small">
            {{-- Nome do edital --}}
            <div class="uk-margin-small">
              <small class="uk-text-muted uk-h7 uk-margin-remove-top"><span uk-icon='arrow-down'></span><i>Título</i></small>
                @if ($errors->has('title'))
                    <small class="uk-text-warning"> –– {{ $errors->first('title') }}</small>
                @endif
              {{Form::text('title', '', ['class' => 'uk-input uk-form-medium uk-text-bold uk-heading', 'style' => 'border-style: dashed'])}}
            </div>


            {{-- Corpo de Texto --}}
            <div class="uk-container uk-container-small">
              <small class="uk-text-muted uk-h7"><span uk-icon='arrow-down'></span><i>Corpo do Texto</i></small>
              @if ($errors->has('body'))
              <small class="uk-text-warning"> –– {{ $errors->first('body') }}</small>
              @endif  

              <div class="uk-container uk-container-large" style="background-color: #eee">
                <div id="toolbar-container"></div>
                <div>
                  {{ Form::hidden('body', '') }} 
                  <textarea name="body" class="form-control my-editor"></textarea>
                </div>
              </div>
            </div>

        </div>



        <!-- /body -->
    </section>
  {!! Form::close() !!}

    <!-- /BOTTOM BAR -->
@endsection

resources/views/pages/cei/internacionalizacao/editais/index.blade.php
@extends('layouts.app')

@section('title')
    UP Maxixe –> CEI -> Editais
@endsection

@php
  /*
    Must init this variable..
    highlight @section('[mobile]menus')
  */
  $isActive = 'cei';
  $isActiveSub = 'cei.int';
  $isActiveSubSub = 'cei.int.editais';

@endphp

@section('menus')
  @include('inc.menus')
  @include('inc.mobilemenus')
@endsection


{{--  The right side of the navbar  --}}
@section('navbar-right-content')
  @auth
    @include('inc.navbar-user')
  @endauth
@endsection


{{--  Body  --}}
@section('body')
  <section class="uk-section uk-section-small">
    <div class="uk-container uk-container-small">
        <h5 class="uk-margin-remove-bottom uk-text-bold uk-h5 uk-margin-remove-adjacent uk-text-muted uk-margin-remove-top">Cooperação e Internacionalização</h5>
        <h1 class="uk-margin-small-bottom uk-text-bold uk-h1 uk-margin-remove-adjacent uk-margin-remove-top">
          Editais
          @auth
            <a href="{{route('editais.create')}}" class="hvr-grow-shadow uk-dark uk-button uk-button-primary uk-border-rounded uk-box-shadow-small uk-float-right" style="position: relative; top: 6.4px;" uk-icon='plus' uk-tooltip="title: Publicar Novo Edital; delay: 300"></a>
          @endauth
        </h1>
        @include('inc.messages')

    </div>
  </section>

  {{-- Apresentação da Repartição --}}
  <section class="uk-section uk-section-muted">
    <div class="uk-container uk-container-small">

      @if (count($editais) > 0)
        @foreach ($editais as $edital)

          @php
            # localize month name to pt.. not the best way, i know... but whatever!
              // retrieve raw edital month
              $monthRaw = $edital->created_at->month;
              // finally translate that shit
              $ptmonth = $months[$monthRaw];
          @endphp


          <article class="uk-section uk-section-small uk-padding-remove-top">
            <header>
              <h2 class="uk-margin-remove-adjacent uk-text-bold uk-margin-small-bottom"><a title="Continuar a ler: '{{$edital->title}}'" class="uk-link-heading" href="{{route('editais.index')}}/{{$edital->id}}">{{$edital->title}}</a></h2>
              <p class="uk-article-meta">
                <span style="position: relative; bottom: 1px" uk-icon="calendar"></span>
                Postado as {{$edital->created_at->format('H:i A')}}, no dia {{$edital->created_at->day}} de {{$ptmonth}} de {{$edital->created_at->year}}
                @if ($edital->created_at->diffInDays(Carbon\Carbon::now()) < 90)
                  <span title="Postado a menos de 3 meses!" style="position: relative; bottom: 1px" class="uk-label uk-label-success uk-border-rounded"><img src="{{ asset('images/icons/blue_dot.svg') }}" style="position: relative; bottom: 1px" uk-svg width="15" height="15"> Recente</span>
                  
                @endif
              </p>
            </header>

            <p style="overflow-wrap: break-word">{!! str_limit(strip_tags($edital->body), $limit = 300, $end = ' [...] ') !!}</p>
            <a class="uk-button uk-button-default uk-button-small hvr-fade" style="border: 1px solid" href="{{route('editais.index')}}/{{$edital->id}}" title="Saber Mais...">Saber mais...</a>
            @auth {{-- Show more options to the event (such as edit and delete) --}}
              <div class="uk-inline uk-padding-small">
                  <span style="cursor: pointer" class="uk-icon-button uk-background-default" uk-icon="more-vertical"></span>
                  <div class="uk-background-default uk-border-rounded" uk-dropdown="mode: click; animation: uk-animation-slide-bottom-small; duration: 150" >
                    <small class="uk-text-bold uk-text-muted">Mais Opções: </small><br>
                    <div class="uk-grid uk-grid-small uk-light" uk-grid>
                      <div>
                        <a href="{{route('editais.index')}}/{{$edital->id}}/edit" class="uk-icon-button uk-background-secondary uk-button-secondary" uk-icon="pencil"></a>
                      </div>

                      <div>
                        {!!Form::open(['action' => ['IntEditaisController@destroy', $edital->id], 'method'=>'POST'])!!}
                          {{Form::hidden('_method', 'DELETE')}}
                          <button type="submit" class="uk-icon-button uk-text-danger uk-button-secondary" uk-icon="trash"></button>
                          {{-- {{Form::submit('Apagar', ['class'=> 'uk-button uk-margin-top uk-button-danger'])}} --}}
                        {!!Form::close()!!}
                      </div>
                    </div>

                  </div>
              </div>
            @endauth
            <hr>
          </article>
        @endforeach
        
      @else
        <div class="uk-margin">
          <div class="uk-card uk-card-small uk-card-default uk-card-body">
            <h6 class="uk-h6 uk-text-muted">
              Nenhum edital postado até então.
            </h6>
          </div>
        </div>
      @endif
    </div>
  </section>
@endsection

resources/views/pages/cei/internacionalizacao/editais/show.blade.php
@extends('layouts.app')

@section('title')
    UP Maxixe –> CEI -> Editais -> ...
@endsection

@php
  /*
    Must init this variable..
    highlight @section('[mobile]menus')
  */
  $isActive = 'cei';
  $isActiveSub = 'cei.int';
  $isActiveSubSub = 'cei.int.editais';

@endphp

@section('menus')
  @include('inc.menus')
  @include('inc.mobilemenus')
@endsection

@section('navbar-right-content')
  @auth
    @include('inc.navbar-user')
  @endauth
@endsection

@section('headcsslink')
  {{ Html::script('../node_modules/@ckeditor/ckeditor5-build-decoupled-document/build/ckeditor.js') }}   

  <style>
    table {
      border-collapse: collapse;
      border-spacing: 0;
      border: 1px double #b3b3b3;
    } 

    tr {
      display: table-row;
      vertical-align: inherit;
      border-color: inherit;
    }

    table td, table th {
      min-width: 2em;
      padding: .4em;
      text-align: center;
      border: 1px solid #d9d9d9;
    }



    blockquote {
      overflow: hidden;
      padding-right: 1.5em;
      padding-left: 1.5em;
      margin-left: 0;
      font-style: italic;
      border-left: 5px solid #ccc;
      font-size: 1.25rem;
      line-height: 1.5;
      color: #333;
      font-family: "Roboto","Helvetica","Arial",sans-serif;
      position: relative;
      font-size: 24px;
      font-weight: 300;
      letter-spacing: .08em;
      display: block;

      -webkit-margin-before: 1em;
      -webkit-margin-after: 1em;
      -webkit-margin-start: 40px;
      -webkit-margin-end: 40px;
    }
  </style>
    
@endsection

{{--  Body  --}}
@section('body')


    {{-- <div class="uk-container uk-visible@m">
        <hr class="uk-margin-remove">
    </div> --}}
    <section class="uk-section uk-margin-remove-bottom uk-section-small uk-text-center">
        <div class="uk-container uk-container-small">
            <!--Message-->
              @include('inc.messages')
            <!--/Message-->
            <a style="position: relative; bottom: 2px;" href="{{route('editais.index')}}" class="uk-button uk-button-default uk-button-primary uk-text-bold uk-border-rounded uk-dark"> <span style="position: relative; bottom: 1px" uk-icon='arrow-left'></span> Voltar àos Editais</a>
        </div>
    </section>

    <!--ARTICLE-->
    <section class="uk-section uk-article uk-section-muted">
        <div class="uk-container uk-container-small">
          <h2 class="uk-text-bold uk-margin-remove-bottom uk-h2">{{$edital->title}}</h2>
          <small class="uk-text-muted uk-h7 uk-margin-remove-adjacent uk-margin-remove-top uk-margin-remove-bottom">
             <a class="uk-button-text uk-link-reset" href="{{route('editais.index')}}">Editais</a>
              / <i>
                    <span style="position: relative; bottom: 1px" uk-icon="calendar"></span>
                    Publicado as {{$edital->created_at->format('H:i\h')}}, no dia {{$edital->created_at->day}} de {{$ptmonth}} de {{$edital->created_at->year}}
                    @auth –– <a href="{{$edital->id}}/edit" class="uk-button uk-button-text uk-text-muted uk-text-bold" style="text-transform: none; position: relative; bottom: 1px">Editar</a> @endauth
                </i>
          </small>
        </div>

        <!-- body -->
        <div class="uk-container uk-container-small">
            <div style="overflow-wrap: break-word">
              <p>{!! $edital->body !!}</p>
            </div>
        </div>
        <!-- /body -->
    </section>

@endsection